### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ryanwmurray** [gianlucadetommaso/Stein-variational-samplers#1]
I believe that there are some files missing to run this. Specifically, I tried to run the double banana file (by first executing load_dir_double_banana.m and then running script_double_banana.m . It couldn't find the function SVN_H. I'm guessing that those files are in the folder "../samplers/stein", which isn't posted on the repository?

**Comment by gianlucadetommaso** [comment]
Dear Ryan,
thank you very much for noting this. The folder was accidentally eliminated during my last edit. It works now.
Best,
Gianluca
