### ISSUE TITLE
What is the observation y you take to get a double banana?

### ISSUE THREAD

**Issue by zt95** [gianlucadetommaso/Stein-variational-samplers#2]
Never mind! The shape does not so depend on the observation, and both a=0.0 and 1.0 works similarly.
----EDIT-----
I want to reproduce your toy experiment for double banana in the paper in python. It seems like the shape of the posterior would heavily depend on your observation y. Could you share which value you take to get those figure? (In code it is just a random variable)

By the way, how is it possible to get a symmetric shape with $x_1 = 0$ in that example, if you take a = 1.0? Is it a typo that we instead should take a = 0.0?

**Comment by gianlucadetommaso** [comment]
Hello,
I strongly apologize somehow I haven't noticed this comment before now!

The observation y is a noisy output of the forward map evaluated at some random true parameter. The forward map is a log Rosenbrock function. The shape of the distribution can vary quite a lot according the true parameter. For other realization the two bananas end up "joining" on the left part of the distribution. Of course the algorithm converges without problems.

I have added a folder with SVN implemented in iPython on several low dimensional test cases. Please feel to play with those, or use that code as a benchmark for yours.

All the best, 
Gianluca

**Comment by zt95** [comment]
Thanks!
