### ISSUE TITLE
BOCPDviaSMC_Hawkes_WannaCry

### ISSUE THREAD

**Issue by nsrishankar** [gianlucadetommaso/Stein-variational-samplers#3]
I'm trying out the code in BOCPDviaSMC_Hawkes on a sensor dataset and am getting an error at this line `rld = stats.rv_discrete( values = ( np.arange( min(t_+1, self.rmax) ), self.rlp ) )` in the `class BOCPD`. I printed out `self.rlp` : 

```
Time: 6
[1.00000000e-02 1.81195171e-04 1.12306196e-02 1.08983524e-02
 1.72809904e-04 9.67517023e-01 0.00000000e+00]
Changepoint at time 6 for drastic decrease
Time: 7
[nan  0.  0.  0.  0.  0. nan  0.]
``` 

Any possible reason why I'd be getting nans (or any way to solve this issue)?

Thanks!

**Comment by gianlucadetommaso** [comment]
The error is likely due to numerical instability of the Hawkes model due to exponential functions. You should probably add some robustness constraints to avoid division by 0 or too large exponents. Rescaling your dataset might be a good option.
